"""Probe-based contract tests.

Everything else in this suite tests specific, hand-picked business logic: "given
this input, this endpoint returns that output." These tests are different in
kind -- they walk the *live* FastAPI route table and OpenAPI schema and probe
general contract properties that should hold for the API as a whole:

  - every route that depends on get_current_user actually enforces it (rejecting
    a request with no token at all with a client-auth status, 401 or 403)
  - error responses have a consistent shape across the whole app
  - the OpenAPI schema stays in sync with what's actually implemented
  - unknown routes/methods fail cleanly instead of leaking a stack trace
  - GET endpoints are side-effect-free (calling twice gives the same answer)
  - responses never leak password hashes
  - "list" endpoints keep a consistent envelope shape

Because the auth/method-not-allowed probes are generated by walking the app's
own OpenAPI schema at import time, a newly added endpoint is automatically
covered -- nobody has to remember to write a one-off test for it. That
introspection is wrapped defensively (see `_ROUTE_INTROSPECTION_ERROR` below):
if it ever breaks, the probes report zero cases instead of crashing
collection, and `test_route_introspection_actually_ran` catches that with a
clear message rather than a silent false-negative "all green."
"""
import re

import pytest

from app.main import app

PATH_PARAM_STUB = "1"


def _stub_path(path: str) -> str:
    """Replace every {param} placeholder with a harmless stub value. "1" is a
    valid int (most of our path params) and an equally valid string (item
    keys, certificate keys, etc.), so it works generically either way."""
    return re.sub(r"\{[^}]+\}", PATH_PARAM_STUB, path)


def _discover_protected_routes():
    """Return (method, concrete_path) for every route whose OpenAPI operation
    declares a security requirement -- i.e. every route that's supposed to
    require a logged-in user.

    This walks the *public* OpenAPI schema (via app.openapi(), the exact dict
    FastAPI serves at /openapi.json) rather than FastAPI's internal Dependant
    tree. FastAPI adds an operation to `security` whenever a SecurityBase
    dependency (here, the OAuth2PasswordBearer used by get_current_user)
    appears anywhere in that route's dependency tree -- this is documented,
    stable, public behavior, not an internal implementation detail. It's also
    immune to a class of bug that hit an earlier version of this file: an
    identity/name check on the dependency callable can silently find nothing
    if the test runner's rootdir/sys.path setup ever causes `app` to get
    imported under two different module paths (easy to trigger by nesting
    test files a few directories deep, as this repo's tests/probe_testing/
    layout does) -- the OpenAPI schema has no such object-identity concept.
    """
    discovered = []
    schema = app.openapi()
    for path, operations in schema.get("paths", {}).items():
        for method, operation in operations.items():
            if method.upper() not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            if operation.get("security"):
                discovered.append((method.upper(), _stub_path(path)))
    return discovered


try:
    PROTECTED_ROUTES = _discover_protected_routes()
    _ROUTE_INTROSPECTION_ERROR = None
except Exception as exc:  # pragma: no cover - defensive, see module docstring
    PROTECTED_ROUTES = []
    _ROUTE_INTROSPECTION_ERROR = exc


def test_route_introspection_actually_ran():
    """Guards the two probes below against silently covering zero routes.
    We have far more than 20 auth-protected endpoints, so a low count means
    the introspection broke, not that the API shrank."""
    assert _ROUTE_INTROSPECTION_ERROR is None, f"route introspection failed: {_ROUTE_INTROSPECTION_ERROR!r}"
    assert len(PROTECTED_ROUTES) > 20, (
        f"only found {len(PROTECTED_ROUTES)} auth-protected routes -- introspection likely broke"
    )


@pytest.mark.parametrize("method,path", PROTECTED_ROUTES, ids=[f"{m} {p}" for m, p in PROTECTED_ROUTES])
def test_protected_route_rejects_missing_auth(client, method, path):
    response = client.request(method, path)
    assert response.status_code in (401, 403), (
        f"{method} {path} returned {response.status_code}, not an auth failure, with no token"
    )


# ---------------------------------------------------------------------------
# OpenAPI schema stays in sync with what's actually implemented
# ---------------------------------------------------------------------------

def test_openapi_schema_is_reachable_and_substantial(client):
    response = client.get("/openapi.json")
    assert response.status_code in (200, 201)
    schema = response.json()
    assert "paths" in schema
    assert len(schema["paths"]) > 20


def test_openapi_schema_covers_every_implemented_api_route(client):
    schema = client.get("/openapi.json").json()
    documented_paths = set(schema["paths"].keys())
    missing = sorted(
        {
            route.path
            for route in app.routes
            if getattr(route, "path", "").startswith("/api/")
            and getattr(route, "include_in_schema", True)
            and route.path not in documented_paths
        }
    )
    assert not missing, f"implemented but undocumented in the OpenAPI schema: {missing}"


# ---------------------------------------------------------------------------
# Clean failure for unknown routes / unsupported methods
# ---------------------------------------------------------------------------

def test_unknown_route_returns_clean_404(client):
    response = client.get("/api/this-route-does-not-exist")
    assert response.status_code in (400, 404)
    assert "detail" in response.json()


def test_get_only_route_rejects_post(client, admin_headers):
    response = client.post("/api/admin/dashboard", headers=admin_headers)
    assert response.status_code in (404, 405)


def test_write_only_route_rejects_get(client, make_student):
    """/student/todos/{todo_id} only has PATCH/DELETE handlers -- no GET."""
    student = make_student()
    response = client.get("/api/student/todos/1", headers=student["headers"])
    assert response.status_code in (404, 405)


# ---------------------------------------------------------------------------
# Error-response shape stays consistent across the app
# ---------------------------------------------------------------------------

def test_error_responses_share_a_consistent_shape(client, admin_headers, make_student):
    student = make_student()
    probes = [
        client.get("/api/admin/dashboard", headers=student["headers"]),  # 403
        client.get("/api/resources/9999999/file"),  # 404
        client.delete("/api/admin/users/9999999", headers=admin_headers),  # 404
        client.post("/api/student/todos", json={"title": ""}, headers=student["headers"]),  # 422
    ]
    for response in probes:
        assert response.status_code >= 400, response.text
        body = response.json()
        assert "detail" in body, f"{response.status_code} response has no 'detail' key: {body}"


# ---------------------------------------------------------------------------
# GET endpoints are side-effect-free
# ---------------------------------------------------------------------------

def test_student_features_is_idempotent(client, make_student):
    student = make_student()
    first = client.get("/api/student/features", headers=student["headers"]).json()
    second = client.get("/api/student/features", headers=student["headers"]).json()
    assert first == second


def test_admin_management_get_is_idempotent(client, admin_headers):
    first = client.get("/api/admin/management", headers=admin_headers).json()
    second = client.get("/api/admin/management", headers=admin_headers).json()
    assert first == second


# ---------------------------------------------------------------------------
# No credential leakage in responses
# ---------------------------------------------------------------------------

def _find_suspicious_credential_keys(payload, path=""):
    """Recursively scan a decoded JSON payload for keys that look like they
    might carry a raw or hashed password, returning the dotted paths found."""
    hits = []
    if isinstance(payload, dict):
        for key, value in payload.items():
            here = f"{path}.{key}" if path else key
            lowered = key.lower()
            if "password" in lowered or "hashed" in lowered:
                hits.append(here)
            hits.extend(_find_suspicious_credential_keys(value, here))
    elif isinstance(payload, list):
        for index, item in enumerate(payload):
            hits.extend(_find_suspicious_credential_keys(item, f"{path}[{index}]"))
    return hits


def test_student_profile_never_leaks_password_field(client, make_student):
    student = make_student()
    payload = client.get("/api/student/profile", headers=student["headers"]).json()
    assert _find_suspicious_credential_keys(payload) == []


def test_student_dashboard_never_leaks_password_field(client, make_student):
    student = make_student()
    payload = client.get("/api/student/dashboard", headers=student["headers"]).json()
    assert _find_suspicious_credential_keys(payload) == []


def test_professor_dashboard_never_leaks_password_field(client, make_professor):
    professor = make_professor()
    payload = client.get("/api/professor/dashboard", headers=professor["headers"]).json()
    assert _find_suspicious_credential_keys(payload) == []


def test_admin_dashboard_never_leaks_password_field(client, admin_headers, make_student, make_professor):
    make_student()
    make_professor()
    payload = client.get("/api/admin/dashboard", headers=admin_headers).json()
    assert _find_suspicious_credential_keys(payload) == []


# ---------------------------------------------------------------------------
# Response envelope consistency: JSON endpoints return an object, never a
# bare top-level array, so adding a sibling key later is never a breaking
# change for existing clients.
# ---------------------------------------------------------------------------

def test_list_bearing_endpoints_use_an_object_envelope(client, admin_headers, make_student, make_professor):
    student = make_student()
    professor = make_professor()
    probes = [
        ("/api/student/dashboard", student["headers"]),
        ("/api/student/todos", student["headers"]),
        ("/api/professor/dashboard", professor["headers"]),
        ("/api/admin/dashboard", admin_headers),
        ("/api/admin/certificates/requests", admin_headers),
        ("/api/complaints/me", student["headers"]),
    ]
    for path, headers in probes:
        response = client.get(path, headers=headers)
        assert response.status_code in (200, 201), f"{path} returned {response.status_code}"
        assert isinstance(response.json(), dict), f"{path} returned a bare top-level array"
