export const STUDY_SUBJECTS = [
  "Mathematics for Data Science I",
  "Statistics for Data Science I",
  "Computational Thinking",
  "English I",
  "Mathematics for Data Science II",
  "Statistics for Data Science II",
  "Programming in Python",
  "English II",
  "Database Management Systems",
  "Programming, Data Structures and Algorithms using Python",
  "Modern Application Development I",
  "Programming Concepts using Java",
  "Modern Application Development II",
  "System Commands",
  "Machine Learning Foundations",
  "Business Data Management",
  "Machine Learning Techniques",
  "Machine Learning Practice",
  "Tools in Data Science",
  "Business Analytics",
  "Introduction to Deep Learning and Generative AI",
];
